browser_user_data = "./chrome_profile"
headless = true
save_filename = "bookmeter_books"
max_search_pages = 30
max_workers = 5
search_keywords = [
    # Bunko
    "ガガガ",
    "ダッシュエックス文庫",
    "光文社文庫",
    "講談社ラノベ",
    "角川つばさ文庫",
    "角川ビーンズ文庫",
    "講談社文庫",
    "MF文庫J",
    "アルファポリス",
    "スターツ",
    "メディアワークス",
    "角川文庫",
    "角川スニーカー文庫",
    "集英社オレンジ文庫",
    "集英社みらい文庫",
    "集英社 文庫",
    "ポプラ",
    "ファンタジア文庫",
    "電撃文庫",
    "ファミ通文庫",
    "宝島社文庫",
    "DREノベルス",
    "カドカワBOOKS",
    "文藝春秋文庫",
    "新文芸",

    # Title keywords
    "ミステリー",
    "ファンタジー",
    "ライトノベル",
    "ラノベ",
    "ライト",
    "君",
    "僕",
    "彼女",
    "彼氏",
    "恋愛",
    "青春",
    "恋愛",
]

[retry]
retry_queue_size = 512
max_retry_count = 3
backoff_factor = 1

[amazon]
enable = false
max_review_pages = 5
