browser_user_data = "./chrome_profile"
save_filename = "bookmeter_books"
max_search_pages = 20
max_workers = 5
search_keywords = [
    "ガガガ",
    "ダッシュエックス文庫",
    "光文社文庫",
    "講談社ラノベ",
    "角川つばさ文庫",
    "角川ビーンズ文庫",
    "講談社文庫",
    "MF文庫J",
    "アルファポリス",
    "スターツ",
    "メディアワークス",
    "角川文庫",
    "角川スニーカー文庫",
    "集英社オレンジ文庫",
    "集英社みらい文庫",
    "ポプラ",
    "ファンタジア文庫",
    "電撃文庫",
    "宝島社文庫",
    "DREノベルス",
    "カドカワBOOKS",
    "文藝春秋文庫",
    "新文芸",
]

[retry]
retry_queue_size = 512
max_retry_count = 3
backoff_factor = 1
